definitions:
  json.AnuncioDestaqueResponse:
    properties:
      descricao:
        type: string
      id:
        type: integer
      imagem:
        type: string
      preco:
        type: number
      titulo:
        type: string
    type: object
  json.LoginRequest:
    properties:
      email:
        type: string
      senha:
        type: string
    type: object
  json.LoginResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      loja:
        $ref: '#/definitions/json.LojaUsuarioResponse'
      nome:
        type: string
      nome_plano:
        type: string
    type: object
  json.LojaUsuarioResponse:
    properties:
      anuncio_destaque:
        $ref: '#/definitions/json.AnuncioDestaqueResponse'
      id:
        type: integer
      nome:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Autentica um usuário e retorna seus dados
      parameters:
      - description: Dados de login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/json.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/json.LoginResponse'
        "400":
          description: Dados inválidos
          schema:
            type: string
        "401":
          description: Não autorizado
          schema:
            type: string
      summary: Login do usuário
      tags:
      - Autenticação
swagger: "2.0"
